# Generated by Django 5.0.2 on 2024-02-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.CharField(max_length=500),
        ),
    ]
